
flyway:
  baseline-on-migrate: true
app:
  datasource:
    jdbc-url: jdbc:postgresql://unsw-study-club.c2tuw1lbakyb.ap-southeast-1.rds.amazonaws.com:5432/unsw2
    username: postgres
    password: xiaoding
    pool-size: 30
server:
  port: 8888
