app:
  datasource:
    jdbc-url: jdbc:postgresql://test.cf8ik1zgfzdt.us-east-2.rds.amazonaws.com:5432/test
    username: postgres
    password: vykanpostgres
    pool-size: 30

server:
  port: 8080

spring:
  flyway:
    #先暂时关闭flyway
    enabled: false
